vcs:
  type: git
  url: ../

cmds:
    - target

workloads:
    - workload.in

postprocessors:
    - name: filter
    - name: normalizer

collectors:
    - name: complexity
      params:
        target_dir: './target'
        files:
           - '../example_sources/workload/main.cpp'
           - '../example_sources/workload/SLList.h'
           - '../example_sources/workload/SLListcls.h'
        rules:
           - 'func1'
           - 'SLList_init'
           - 'SLList_insert'
           - 'SLList_search'
           - 'SLList_destroy'
           - 'SLListcls'
           - '~Sllistcls'
           - 'Insert'
           - 'Remove'
           - 'Search'
        internal_data_filename: 'trace.log'
        init-storage-size: 20000
    - name: complexity
      params:
        target_dir: './target'
        files:
           - '../example_sources/workload/main.cpp'
           - '../example_sources/workload/SLList.h'
           - '../example_sources/workload/SLListcls.h'
        rules:
           - 'func1'
           - 'SLList_init'
           - 'SLList_insert'
           - 'SLList_search'
           - 'SLList_destroy'
           - 'SLListcls'
           - '~Sllistcls'
           - 'Insert'
           - 'Remove'
           - 'Search'
        internal_data_filename: 'trace.log'
        init-storage-size: 20000
        sampling:
          - func: 'SLList_insert'
            sample: 1
